---
title: "STT5100 #9 - Regression Poisson"
author: "Arthur Charpentier"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
base = read.table("http://freakonometrics.free.fr/baseaffairs.txt",header=TRUE)
str(base)
table(base$Y)
df=data.frame(y=base$Y,
              religion=as.factor(base$RELIGIOUS),
              occupation=as.factor(base$OCCUPATION),
              expo = 1)

(E=xtabs((y>=0)~religion+occupation,data=df))
(N=xtabs(y~religion+occupation,data=df))
sum(N)/sum(E)
A=rep(1,length(levels(df$religion)))
B=rep(1,length(levels(df$occupation)))*sum(N)/sum(E)
A
B
E * A%*%t(B)
sum(B*E[1,])
sum(B*E[2,])
apply(t(B*t(E)),1,sum)
sum(A*E[,1])
sum(A*E[,2])
apply(A*E,2,sum)
A=apply(N,1,sum)/apply(t(B*t(E)),1,sum)
B=apply(N,2,sum)/apply(A*E,2,sum)
A
B

for(i in 1:1000){
  A=apply(N,1,sum)/apply(t(B*t(E)),1,sum)
  B=apply(N,2,sum)/apply(A*E,2,sum)
}
A
B
E * A%*%t(B)

apply(N,1,sum)
apply(E * A%*%t(B),1,sum)

apply(N,2,sum)
apply(E * A%*%t(B),2,sum)

reg=glm(y~religion+occupation,data=df,family=poisson)
summary(reg)

yp = predict(reg,type="response")
sum(yp)
sum(df$y)
xtabs(yp~df$religion+df$occupation)
E * A%*%t(B)


a=exp(coefficients(reg)[1]+c(0,coefficients(reg)[2:5]))
a/a[1]
A/A[1]
b=exp(coefficients(reg)[1]+c(0,coefficients(reg)[6:11]))
b/b[1]
B/B[1]

yp = predict(reg,type="response")
xtabs(yp~df$religion+df$occupation)
E * A%*%t(B)
```

```{r}
library(boot)
data(aids)
reg=glm(y~as.factor(delay)+as.factor(time),data=aids)

D=unique(aids$delay)
T=unique(aids$time)
T2=unique(aids$year+(aids$quarter-1/2)/4)
M=matrix(NA,length(T2),length(D))
for(i in 1:length(T2)){
  for(j in 1:length(D)){
    M[i,j]=aids[(aids$time==i)&(aids$delay==D[j]),"y"]}}
for(i in 1:(length(D)-2)){
  M[nrow(M)+1-i,(2+i):length(D)]=NA
}
M

aids2=aids
aids2$y[aids2$dud==1]=NA
reg=glm(y~as.factor(delay)+as.factor(time),data=aids2,family=poisson)
summary(reg)
```